name: ⚡ Implementation & Development
description: Bug fixes, technical tasks, and development improvements
title: "[DEV] "
labels: ["development", "implementation", "body"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ Body Domain - Implementation & Development
        Use this template for bug fixes, technical implementation, and development tasks.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of development work is this?
      options:
        - Bug Fix
        - Feature Implementation
        - Performance Optimization
        - Technical Debt
        - Testing Improvement
        - CI/CD Enhancement
        - Developer Experience
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the technical work needed
      placeholder: Describe the implementation requirements, bug, or technical improvement...
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Technical specifications and implementation notes
      placeholder: |
        - Files to modify
        - Functions/classes affected
        - Dependencies required
        - Breaking changes (if any)
    validations:
      required: false

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps (for bugs)
      description: Steps to reproduce the issue
      placeholder: |
        1. Step 1
        2. Step 2
        3. Expected vs actual behavior
    validations:
      required: false

  - type: textarea
    id: test_plan
    attributes:
      label: Test Plan
      description: How should this be tested?
      placeholder: |
        - Unit tests needed
        - Integration tests
        - Manual testing steps
        - Performance benchmarks
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex is this implementation?
      options:
        - Simple (< 1 day)
        - Medium (1-3 days)
        - Complex (3-7 days)
        - Epic (> 1 week)
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Implementation Requirements
      description: What needs to be done?
      options:
        - label: Code implementation
        - label: Unit tests
        - label: Integration tests
        - label: Documentation update
        - label: Performance testing
        - label: Breaking change review
