name: Feature Request
description: Suggest a new feature for the QNCE Engine
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: Describe the feature you'd like...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
