name: 🔒 Security Vulnerability
description: Report a security vulnerability in QNCE Engine
labels: ["security", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **Please do not report security vulnerabilities in public issues.**
        
        For security vulnerabilities, please use GitHub's private vulnerability reporting feature:
        [Report a Security Vulnerability](https://github.com/ByteSower/qnce-engine/security/advisories/new)
        
        This issue template is for security-related discussions that are not sensitive vulnerabilities.

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Security Enhancement Request
        - Security Documentation
        - Security Tool/Process
        - General Security Discussion
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of QNCE Engine are affected?
      placeholder: "e.g., 1.3.x, all versions, etc."
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the security concern or enhancement
      placeholder: Describe the security issue or enhancement request...
    validations:
      required: true

  - type: textarea
    id: security-impact
    attributes:
      label: Security Impact
      description: What is the potential security impact or benefit?
      placeholder: Describe the security implications...
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Do you have suggestions for addressing this security concern?
      placeholder: Describe potential solutions or improvements...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the security issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Security Policy Acknowledgment
      description: Please confirm you have read our security policy
      options:
        - label: I have read the [Security Policy](https://github.com/ByteSower/qnce-engine/blob/main/SECURITY.md)
          required: true
        - label: This is NOT a sensitive security vulnerability (those should be reported privately)
          required: true