name: QNCE Engine CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Quality
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
      
    - name: Test CLI tools
      run: |
        # Test qnce-init
        npx qnce-init test-project
        cd test-project
        # Test qnce-audit
        npx qnce-audit story.json
        cd ..
        rm -rf test-project

  performance:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run performance tests
      run: |
        # Performance test script (to be implemented)
        node -e "
        const { createQNCEEngine, DEMO_STORY } = require('./dist/index.js');
        const engine = createQNCEEngine(DEMO_STORY);
        
        console.time('100-transitions');
        for(let i = 0; i < 100; i++) {
          const choices = engine.getAvailableChoices();
          if(choices.length > 0) {
            engine.selectChoice(choices[0]);
          }
        }
        console.timeEnd('100-transitions');
        "

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [test, performance]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: github.event_name == 'push' && contains(github.event.head_commit.message, '[publish]')
      
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[publish]')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get package version
      id: package-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: QNCE Engine v${{ steps.package-version.outputs.version }}
        body: |
          ## What's New in v${{ steps.package-version.outputs.version }}
          
          See the [CHANGELOG](CHANGELOG.md) for detailed changes.
          
          ## Installation
          ```bash
          npm install qnce-engine@${{ steps.package-version.outputs.version }}
          ```
        draft: false
        prerelease: false
